driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  synced_folders:
    - ["/tmp/opscode-analytics", "/etc/opscode-analytics"]

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[test::apt]
- name: ubuntu-12.04
  run_list:
    - recipe[test::apt]
- name: ubuntu-14.04
  run_list:
    - recipe[test::apt]
- name: centos-6.6
- name: centos-5.10
- name: centos-5.11

suites:
- name: standalone
  run_list:
  - recipe[test::hostsfile]
  - recipe[chef-server]
  - recipe[chef-server::add_ons]
  - recipe[test::user_and_org]
  driver:
    vm_hostname: chef.example.com
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'
      add_ons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server
      configuration:
        oc_id:
          applications:
            analytics:
              redirect_uri: 'https://analytics.example.com/'
        rabbitmq:
          vip: '33.33.33.10'
          node_ip_address: '0.0.0.0'

- name: analytics
  run_list:
  - recipe[test::hostsfile]
  - recipe[chef-server::analytics]
  driver:
    vm_hostname: analytics.example.com
    network:
      - ['private_network', {ip: '33.33.33.11'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'

