driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[test::apt]
- name: ubuntu-12.04
  run_list:
    - recipe[test::apt]
- name: ubuntu-14.04
  run_list:
    - recipe[test::apt]
- name: centos-6.6
- name: centos-5.10
- name: centos-5.11

suites:
- name: standalone
  run_list:
  - recipe[chef-server]
  - recipe[chef-server::add_ons]
  - recipe[test::user_and_org]
  driver:
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: ''
      add_ons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server

- name: analytics
  run_list:
  - recipe[chef-server]
  - recipe[chef-server::add_ons]
  driver:
    network:
      - ['private_network', {ip: '33.33.33.11'}]
  attributes:
    chef-server:
      api_fqdn: ''
      add_ons:
        - opscode-analytics

- name: fqdn
  run_list:
  - recipe[test]
  - recipe[chef-server]
  - recipe[test::post-install]
  attributes:
    chef-server:
      api_fqdn: 'chef-server-tk.example.com'

- name: no-fqdn
  run_list:
  - recipe[test]
  - recipe[chef-server]
  - recipe[chef-server::add_ons]
  driver:
    network:
      - ['private_network', {ip: '33.33.33.12'}]
  attributes:
    chef-server:
      api_fqdn: ''